image: mambaorg/micromamba:jammy
cache:
    # Cache pip/conda downloads
    paths:
        - /opt/conda/pkgs/
        - .cache/pip

tests:
  script:
    # Create env
    - micromamba install -y -n base -f environment.yml

    # Install gl depends and add path to load conda libs
    - micromamba install -y -n base -c conda-forge \
        mesa-libegl-devel-cos7-x86_64 \
        mesa-libgl-devel-cos7-x86_64 \
        mesa-libgbm-cos7-x86_64 \
        libx11-devel-cos7-x86_64 \
        libxext-devel-cos7-x86_64 \
        libxrender-devel-cos7-x86_64 \
        libxdamage-devel-cos7-x86_64 \
        libxfixes-devel-cos7-x86_64 \
        libxxf86vm-devel-cos7-x86_64 \
        freetype-devel-cos7-x86_64 \
        fontconfig-devel-cos7-x86_64 \
        libxshmfence-devel-cos7-x86_64 \
        libxcb-devel-cos7-x86_64 \
        libpng-devel-cos7-x86_64 \
        libxau-devel-cos7-x86_64 \
        glib2-devel-cos7-x86_64 \
        libxkbcommon \
        dbus
    - export LD_LIBRARY_PATH="/opt/conda/x86_64-conda-linux-gnu/sysroot/usr/lib:/opt/conda/lib"
    - ln -s /opt/conda/x86_64-conda-linux-gnu/sysroot/usr/lib64/libEGL_mesa.so.0 /opt/conda/x86_64-conda-linux-gnu/sysroot/usr/lib/libEGL.so.1

    # Wayland
    - micromamba install -y -n base -c dtk-forge6 -c conda-forge wayland

    # Create env
    - micromamba install -y -n base -f environment.yml
    - pip install -e ./

    # Test Qt
    - export QT_QPA_PLATFORM=xcb
    - export FORCE_QT_API=pyqt6
    - python -c "from PyQt6 import QtWidgets"

    # Install testing utils
    - pip install pytest pytest-coverage pytest-qt enaml-coverage-plugin

    # Install qa tools
    - pip install black flake8 isort mypy

    # Run
    - pytest tests -v --cov declaracad
    #- xvfb-run -s "-screen 0 1920x1080x24 +extension GLX +extension RENDER" gdb -ex run -ex bt -ex quit --args python -m pytest tests -v -s

    # Run checks
    - isort --check --diff declaracad
    - black --check --diff declaracad
    - yes | mypy declaracad --install-types || true
    - mypy declaracad --ignore-missing-imports
    - flake8 --ignore=E203,E266,E501,W503,E731 declaracad
