image: mambaorg/micromamba:0.27.0

tests:
  script:
    - export

    # Create env
    - micromamba install -y -n base -f environment.yml

    # Activate env
    - micromamba install -y -n base mesa-libgl-devel-cos6-x86_64 libxi-devel-cos6-x86_64 libxext-devel-cos6-x86_64

    # Install declaracad
    - pip install -e .

    # Install testing utils
    - pip install pytest pytest-coverage pytest-qt enaml-coverage-plugin

    # Install qa tools
    - pip install black flake8 isort mypy

    # Make Qt Happy
    # - export QT_DEBUG_PLUGINS=1
    - export QT_QPA_PLATFORM=xcb

    # Run
    - pytest tests -v --cov declaracad
    #- xvfb-run -s "-screen 0 1920x1080x24 +extension GLX +extension RENDER" gdb -ex run -ex bt -ex quit --args python -m pytest tests -v -s

    # Run checks
    - isort --check --diff declaracad
    - black --check --diff declaracad
    - yes | mypy declaracad --install-types || true
    - mypy declaracad --ignore-missing-imports
    - flake8 --ignore=E203,E266,E501,W503,E731 declaracad
