image: continuumio/miniconda3:latest

tests:
  script:
    - apt-get update -q -y
    - apt-get install -y libgl1-mesa-glx

    # Create env
    - conda env create -f environment.yml

    # Reinit
    - conda init bash
    - source ~/.bashrc

    # Activate env
    - source activate declaracad
    - conda info

    # Install declaracad
    - pip install -e .

    # Force copy libs, wtf???
    - cp /opt/conda/envs/declaracad/lib/*.so /usr/lib/x86_64-linux-gnu/
    - cp /opt/conda/envs/declaracad/lib/*.so.* /usr/lib/x86_64-linux-gnu/

    # Install testing utils
    - pip install pytest pytest-coverage pytest-qt
    - pytest tests -v --cov declaracad
