name: declaracad

channels:
 - conda-forge
 - defaults
 - https://repo.codelv.com

dependencies:
 - python =3.12
 - cxx-compiler
 - pybind11
 - pyocct >=7.9
 - pyside6
 - sel(linux): qt6-wayland
 - cx_Freeze
